# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/src/Services/SKSGroupF.SKS.Package.Services'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    projects: '**/*.csproj'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '**/SKSGroupF.SKS.Package.Services.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: DotNetCoreCLI@2
  displayName: 'Build Tests'
  inputs:
    command: build
    projects: '**/*Tests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'

- task: reportgenerator@4
  displayName: "Merge code coverage reports"
  inputs:
    reports: "**/coverage.cobertura.xml"
    targetdir: "$(Build.ArtifactStagingDirectory)/coverlet"
    reporttypes: "Cobertura"
    verbosity: "Verbose"

- task: PublishCodeCoverageResults@1
  displayName: "Publish code coverage results"
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "$(Build.ArtifactStagingDirectory)/coverlet/Cobertura.xml"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'